server:
  port: 8110
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: woj-backend-user-service
          uri: lb://woj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: woj-backend-question-service
          uri: lb://woj-backend-question-service
          predicates:
              - Path=/api/question/**
        - id: woj-backend-judge-service
          uri: lb://woj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: woj-backend-file-service
          uri: lb://woj-backend-file-service
          predicates:
            - Path=/api/file/**
        - id: woj-backend-post-service
          uri: lb://woj-backend-post-service
          predicates:
            - Path=/api/post/**
  application:
    name: woj-backend-gateway
  main:
    web-application-type: reactive
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2

